### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by kddubey** [amanjain454/4741-Project#3]
The project is about determining a pricing algorithm for a home-office-home commute subscription service. The goal of this algorithm is to increase commute reliability during office hours while not significantly reducing profits for companies providing these services (e.g. Moveinsync).

The authors are using six different datasets provided by Moveinsync. The information stored in these datasets includes user specific features as well as commute availabilities, constraints, and operational costs. 

Three things I like about the proposal are:
1. Usefulness: an algorithm that would achieve the authors' objective is highly useful to the real world. Furthermore, their framework may be applicable to any pricing problem where the goal is to balance customer satisfaction and business profits. 

2. Complexity: pricing is framed more as a complex optimization problem than a straightforward supervised learning one; there is no exact score corresponding to balancing commute reliability and Moveinsync profits, and no single dataset that could answer the question. This reflects the ambiguous and challenging nature of applied problems. 

3. Planning: the proposal includes the scope of their project and assumptions they make about the problem. The authors have also done their homework on understanding each of the datasets and APIs. 

Three areas for improvement are:
1. Magnitude of problem: try to quantify the unreliability of home-office-home commute services in India today, and Moveinsync's profits. This will give you a baseline to compare against for your final pricing algorithm. 

2. Algorithm planning: it may help to more rigorously define the algorithms (in terms of inputs and outputs) that you will develop along the way, and explain how each of them will be integrated into your final pricing scheme. 

3. Data planning: The flow diagram is a good start for how you will merge information across customers and companies. It may help you to more explicitly state how one dataset relates to the next.

**Comment by amanjain454** [comment]
Thanks for your kind feedback. We have taken note of suggestions and have already implemented some of these in midterm report.
