### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by yizhouyu** [amanjain454/4741-Project#4]
This project is about pricing a cab subscription service. The data that the group members are using contains features such as user-specific attributes, trip attributes, cab attributes, location data, and pricing data. This group tries to use big data to decide how to price the X days subscription program for home-office-home commutes for a retail user. 

Like: 
The project will be a mix of data analysis and algorithm development. It would be exciting to see specific algorithms that work best on location and pricing data that this team is dealing with. 
The project also involves understanding feedback of customers on pricing, which should be an interesting part of this project that involves natural language processing and could generate some unique insights.
The team will try to understand different pricing philosophies: premium, penetration, economic, and behavioral.  So this will be an interdisciplinary study that also touches concepts in economics.

Areas for improvement:
It seems the group is using a lot of features. In your implementation you should think of how you can identify features that are irrelevant and only keep those features that are relevant.
Because you are using a lot of features, it would be helpful to find a way to plot certain features (geolocation data, etc) and the correlation among multiple features. This will help you and the audience understand the data better.
It would be helpful if you can set your evaluation metric more explicitly. Maybe you can define a way to calculate a score on your model, or find some other models that serve as benchmark that you can compare against.

**Comment by amanjain454** [comment]
Thanks for your kind feedback. We have taken note of suggestions and have already implemented some of these in midterm report.
