### ISSUE TITLE
peer review by yw2272

### ISSUE THREAD

**Issue by wangyuze11** [amanjain454/4741-Project#5]
Yw2272
Pricing of cab subscription service
This group is using a dataset, consisting of 6 fields of data:user attribute, trip attribute, cabs attributes, cabs contract attributes, foursquare APIs and uber pricing API , to price the X days subscription program for home-office-home commutes for a retail user. They will accomplish this goal by following the charts and steps designed in the proposal, including understanding data, preprocessing data, consuming route data, understanding cost, etc. To balance between service of quality with cost of service, they will also utilize different pricing philosophies like premium, penetration and economic, etc. Finally, they will suggest the pricing strategy for retail users.
Three things we like the most are:
1.They provide a detailed explanation of the data set. Make readers understand your project easily.
2.They show us the scope and assumptions for this proposal and it will make this project more accurate.
3.Their investigation for this question is very detailed and meaningful with lots of steps that we can follow.
Three areas for improvement:
1.The length of the proposal is a bit too long, and the charts take too many spaces. Maybe considering explaining various things in words.
2.It’s maybe difficult for common readers to understand and interpret the result due to the amount and depth of this dataset.
3.It would be more helpful if they specify in more detail about techniques for this dataset.

**Comment by amanjain454** [comment]
Thanks for your kind feedback. We have taken note of suggestions and have already implemented some of these in the midterm report.
